### ISSUE TITLE
显示哈希值错误，为什么

### ISSUE THREAD

**Issue by Drawlone** [JustYoomoon/WechatDecrypt#2]

**Comment by bianliangpai** [comment]
我这边也遇到了相同的问题
注意到 wechat.cpp 文件开头定义了不少宏数值，简单搜了一下，这些数值并不是绝对不变的
猜测可能跟不同环境下宏的数值不同有关

**Comment by IndiaZhangSan** [comment]
解不了，密钥是更新的，需要自己抓，他这是写死的
仔细看了一下源码，有些值不对，应该解不了MSG开头的微信数据库
